# action.yml
name: "Wait on check"
author: "progapandist"
description: "Wait on a certain check to pass for commit"
inputs:
  allowed-conclusions:
    description: "Array of allowed conclusions"
    required: false
    default: success,skipped
  ignore-checks:
    description: "Array of ignore checks"
    required: false
    default: ""
  check-name:
    description: "A name of a check that has to pass"
    required: false
    default: ""
  check-regexp:
    description: "Filter checks to wait using Regexp"
    required: false
    default: ""
  ref:
    description: "A git ref to be checked: branch/tag/commit sha"
    required: true
  repo-token:
    description: "A GitHub token for the repo"
    required: false
    default: ""
  wait-interval:
    description: "Seconds to wait between Checks API requests"
    required: false
    default: "10"
  api-endpoint:
    description: "Github API Endpoint to use."
    required: false
    default: ""
  running-workflow-name:
    description: "Name of the workflow to be ignored (the one who is waiting for the rest)"
    required: false
    default: ""
  verbose:
    description: "Print logs if true"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Not needed with a .ruby-version file

    - name: Cache Ruby Gems
      uses: actions/cache@v4
      with:
        path: ${{ github.action_path }}
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-

    - name: Bundle Install
      run: |
        bundle install --jobs 4 --retry 3
      working-directory: ${{ github.action_path }}
      shell: bash

    - run: |
        ruby entrypoint.rb
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        ALLOWED_CONCLUSIONS: ${{ inputs.allowed-conclusions }}
        IGNORE_CHECKS: ${{ inputs.ignore-checks }}
        CHECK_NAME: ${{ inputs.check-name }}
        CHECK_REGEXP: ${{ inputs.check-regexp }}
        REF: ${{ inputs.ref }}
        REPO_TOKEN: ${{ inputs.repo-token }}
        VERBOSE: ${{ inputs.verbose }}
        WAIT_INTERVAL: ${{ inputs.wait-interval }}
        RUNNING_WORKFLOW_NAME: ${{ inputs.running-workflow-name }}
        API_ENDPOINT: ${{ inputs.api-endpoint }}
branding:
  icon: "check-circle"
  color: "green"
