fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.7.2     # default: RUBY_VERSION
default_ignores: false  # default: true
