name: Install
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

    - name: Set the ruby version
      uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1
      with:
        ruby-version: 3.2
        bundler-cache: true
        
    - name: Install npm dependencies
      shell: bash
      run: npm install cspell husky prettier

    - name: Install PyPI dependencies
      shell: bash
      run: pip install bump2version trufflehog3
