name: Workflow to wait on

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: 'Time to delay'
        required: false
        default: "120"

jobs:
  wait-on-me:
    runs-on: ubuntu-latest

    steps:
      - name: Do some busywork
        env:
          default_delay: "120"
          input_delay: ${{ github.event.inputs.delay_seconds }}
        run: |
          [ "$input_delay" ] && sleep_for="$input_delay" || sleep_for="$default_delay"
          sleep $sleep_for

      - name: Report success
        run: echo 'Done with busywork'
