name: Wait omitting check-name
on:
  workflow_dispatch:
  push:

jobs:
  wait-omitting-check-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait on tests
        uses: ./
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
          running-workflow-name: wait-omitting-check-name

      - name: Success
        run: echo 'success!'
